{"name": "Проверка ошибок аутентификации при неполных данных", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected response: {'code': 400, 'message': 'Недостаточно данных для входа'}\nassert {'code': 400,...ых для входа'} == {'message': '...ых для входа'}\n  \n  Omitting 1 identical items, use -vv to show\n  Left contains 1 more item:\n  {'code': 400}\n  Use -v to get more diff", "trace": "self = <tests.test_authorization_courier.TestCourierLogin object at 0x000001CA8F699940>\nregister_new_courier = (<Response [201]>, {'firstName': 'ervyrczitr', 'login': 'tikrddjplr', 'password': 'rhhnujmazw'}, 499577), login = '', password = ''\nmessage = 'Недостаточно данных для входа'\n\n    @allure.title('Проверка ошибок аутентификации при неполных данных')\n    @allure.description('Тестирование случаев пропуска обязательных полей')\n    @pytest.mark.parametrize(\"login, password, message\", [\n        (\"\", \"valid_password\", \"Недостаточно данных для входа\"),\n        (\"valid_login\", \"\", \"Недостаточно данных для входа\"),\n        (\"\", \"\", \"Недостаточно данных для входа\")\n    ])\n    \n    def test_courier_login_missing_fields(self, register_new_courier, login, password, message):\n        with allure.step(\"Получить данные зарегистрированного курьера\"):\n            response, registered_payload, courier_id = register_new_courier\n    \n        with allure.step(\"Подготовить тестовые данные\"):\n            if password == \"valid_password\":\n                password = registered_payload['password']\n            if login == \"valid_login\":\n                login = registered_payload['login']\n    \n            payload = {\n                'login': login,\n                'password': password\n            }\n            allure.attach(f\"Test data - login: '{login}', password: '{password}'\", name=\"Test Parameters\")\n    \n        with allure.step(\"Отправить запрос с неполными данными\"):\n            response = requests.post(Urls.url_courier_login, data=payload)\n            allure.attach(f\"Response: {response.text}\", name=\"Response Data\")\n    \n        with allure.step(\"Проверить статус код 400\"):\n            assert response.status_code == 400, f\"Unexpected status code: {response.status_code}\"\n    \n        with allure.step(\"Проверить сообщение об ошибке\"):\n            response_json = response.json()\n>           assert response_json == {'message': message}, f\"Unexpected response: {response_json}\"\nE           AssertionError: Unexpected response: {'code': 400, 'message': 'Недостаточно данных для входа'}\nE           assert {'code': 400,...ых для входа'} == {'message': '...ых для входа'}\nE             \nE             Omitting 1 identical items, use -vv to show\nE             Left contains 1 more item:\nE             {'code': 400}\nE             Use -v to get more diff\n\ntests\\test_authorization_courier.py:70: AssertionError"}, "description": "Тестирование случаев пропуска обязательных полей", "steps": [{"name": "Получить данные зарегистрированного курьера", "status": "passed", "start": 1744268489244, "stop": 1744268489244}, {"name": "Подготовить тестовые данные", "status": "passed", "attachments": [{"name": "Test Parameters", "source": "43d78684-fb3f-4218-a7c4-962e1a0c294b-attachment.attach"}], "start": 1744268489244, "stop": 1744268489244}, {"name": "Отправить запрос с неполными данными", "status": "passed", "attachments": [{"name": "Response Data", "source": "15db9c95-d8fd-4368-8f78-c1842cc14434-attachment.attach"}], "start": 1744268489244, "stop": 1744268489319}, {"name": "Проверить статус код 400", "status": "passed", "start": 1744268489319, "stop": 1744268489319}, {"name": "Проверить сообщение об ошибке", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected response: {'code': 400, 'message': 'Недостаточно данных для входа'}\nassert {'code': 400,...ых для входа'} == {'message': '...ых для входа'}\n  \n  Omitting 1 identical items, use -vv to show\n  Left contains 1 more item:\n  {'code': 400}\n  Use -v to get more diff\n", "trace": "  File \"C:\\Users\\Aleksandra\\PycharmProjects\\Sprint_7\\tests\\test_authorization_courier.py\", line 70, in test_courier_login_missing_fields\n    assert response_json == {'message': message}, f\"Unexpected response: {response_json}\"\n"}, "start": 1744268489319, "stop": 1744268489320}], "parameters": [{"name": "login", "value": "''"}, {"name": "password", "value": "''"}, {"name": "message", "value": "'Недостаточно данных для входа'"}], "start": 1744268489244, "stop": 1744268489321, "uuid": "76e50834-c786-450e-8b13-b7a5c4d89920", "historyId": "5d16c46d3235a628cc30fd8188169502", "testCaseId": "4f31af8384108993f6dff4ee6bb659fb", "fullName": "tests.test_authorization_courier.TestCourierLogin#test_courier_login_missing_fields", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authorization_courier"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-HIR29C3"}, {"name": "thread", "value": "13920-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authorization_courier"}]}